const p = (slug, page) => `./public/products/${slug}-p${page}.png`;

const bikesData = [
  {
    id: "bike-1",
    name: "26 Inches Foldable Fat Bicycle",
    price: "₹14,999",
    shortDescription: "Premium 26-inch foldable fat tyre bicycle — portable, sturdy, and perfect for urban commuting and adventure trails.",
    fullDescription: "The 26 Inches Foldable Fat Bicycle combines the convenience of a foldable frame with the stability and grip of fat tyres. Its 26-inch wheels with wide tyres absorb bumps and provide excellent traction on various surfaces including city roads, gravel paths, and park trails. The quick-fold mechanism allows you to collapse the bike in seconds, making it perfect for commuters who need a compact ride that can be easily stored in apartments, offices, or car boots.",
    images: [
      p("26-inches-foldable-fat-bicycle", 1),
      p("26-inches-foldable-fat-bicycle", 2),
      p("26-inches-foldable-fat-bicycle", 3),
      p("26-inches-foldable-fat-bicycle", 4),
      p("26-inches-foldable-fat-bicycle", 5),
      p("26-inches-foldable-fat-bicycle", 6),
    ],
    specifications: {
      "Wheel Size": "26\" Fat Tyre",
      "Frame Material": "Foldable Steel Frame",
      "Braking System": "Front & Rear Disc Brakes",
      "Gearbox": "Single Speed",
      "Kerb Weight": "16 kg",
      "Folded Dimensions": "75 x 60 x 35 cm",
      "Max Load Capacity": "110 kg",
      "Tyres Type": "26\" x 4.0\" All-Terrain Fat",
    },
    features: ["Quick Fold Mechanism","Fat Tyres for All Terrain","Front & Rear Disc Brakes","Lightweight 16 kg","Adjustable Seat Height","Sturdy Kickstand","Easy Carry Handle"],
    colors: ["Orange","Gold","Yellow"],
    inStock: true,
    category: "Bicycles",
  },
  {
    id: "bike-2",
    name: "26 Inches BMW Foldable Bicycle",
    price: "₹13,999",
    shortDescription: "BMW-inspired 26-inch foldable bicycle with premium design — style meets everyday practicality.",
    fullDescription: "The 26 Inches BMW Foldable Bicycle brings iconic BMW design language to the cycling world. With its sleek frame, premium paint finish, and intelligent folding mechanism, it stands out as a fashion-forward yet highly functional ride. The 26-inch wheels provide a comfortable ride height for adults, while the compact fold makes storage and transport effortless. Ideal for daily commuters, campus riders, and anyone who values both style and convenience.",
    images: [
      p("26-inches-bmw-foldable-bicyle", 1),
      p("26-inches-bmw-foldable-bicyle", 2),
      p("26-inches-bmw-foldable-bicyle", 3),
      p("26-inches-bmw-foldable-bicyle", 4),
      p("26-inches-bmw-foldable-bicyle", 5),
      p("26-inches-bmw-foldable-bicyle", 6),
      p("26-inches-bmw-foldable-bicyle", 7),
      p("26-inches-bmw-foldable-bicyle", 8),
      p("26-inches-bmw-foldable-bicyle", 9),
    ],
    specifications: {
      "Wheel Size": "26\"",
      "Frame Material": "Foldable Alloy Frame",
      "Braking System": "Front & Rear Disc Brakes",
      "Gearbox": "21-Speed Shimano Drivetrain",
      "Kerb Weight": "14 kg",
      "Folded Dimensions": "70 x 55 x 30 cm",
      "Max Load Capacity": "100 kg",
      "Design Theme": "BMW Sport Inspired",
    },
    features: ["BMW-Inspired Design","Quick Fold Mechanism","21-Speed Shimano Gears","Premium Disc Brakes","Lightweight Alloy Frame","Multiple Color Options","Adjustable Handlebar & Seat"],
    colors: ["Red","Blue","Gold","Orange"],
    inStock: true,
    category: "Bicycles",
  },
  {
    id: "bike-3",
    name: "500cc ATV",
    price: "₹5,30,000",
    shortDescription: "Powerful 500cc all-terrain vehicle — built for serious off-road domination and adventure.",
    fullDescription: "The 500cc ATV is a beast of an all-terrain vehicle designed for serious off-road enthusiasts who demand maximum power and capability. Its massive 500cc engine delivers exhilarating performance across all terrains — from muddy trails and rocky paths to sandy dunes and forest tracks. With aggressive styling, robust suspension, and four-wheel drive capability, this ATV is ready to conquer any landscape you throw at it. Whether for farm work, trail riding, or pure adrenaline-fueled adventure, the 500cc ATV is the ultimate off-road machine.",
    images: [
      p("500cc-atv", 1),
      p("500cc-atv", 2),
      p("500cc-atv", 3),
      p("500cc-atv", 4),
      p("500cc-atv", 5),
      p("500cc-atv", 6),
      p("500cc-atv", 7),
    ],
    specifications: {
      "Engine Type": "500cc, 4-Stroke, Single Cylinder",
      "Transmission": "Automatic CVT with Reverse",
      "Drive System": "4WD / 2WD Selectable",
      "Braking System": "Front & Rear Hydraulic Disc",
      "Fuel Tank Capacity": "15 L",
      "Kerb Weight": "320 kg",
      "Max Load Capacity": "200 kg",
      "Ground Clearance": "250 mm",
    },
    features: ["500cc Powerful Engine","4WD / 2WD Selectable","Automatic Transmission","Hydraulic Disc Brakes","Long-Travel Suspension","Aggressive Off-Road Tyres","High Ground Clearance","Reverse Gear"],
    colors: ["Red","Gold"],
    inStock: true,
    category: "ATV",
  },
  {
    id: "bike-4",
    name: "300cc Panther ATV",
    price: "₹3,20,000",
    shortDescription: "Versatile 300cc Panther ATV — the perfect balance of power, agility, and off-road performance.",
    fullDescription: "The 300cc Panther ATV strikes the perfect balance between raw power and nimble handling, making it the most versatile all-terrain vehicle in our lineup. Its 300cc engine provides ample power for climbing steep inclines and powering through tough terrain, while the lightweight chassis ensures sharp handling and easy maneuverability. The Panther styling gives it an aggressive, predatory appearance that matches its capable performance on trails, farms, and adventure paths.",
    images: [
      p("300cc-panther-atv", 1),
      p("300cc-panther-atv", 2),
      p("300cc-panther-atv", 3),
      p("300cc-panther-atv", 4),
      p("300cc-panther-atv", 5),
      p("300cc-panther-atv", 6),
      p("300cc-panther-atv", 7),
    ],
    specifications: {
      "Engine Type": "300cc, 4-Stroke, Single Cylinder",
      "Transmission": "Automatic with Reverse",
      "Drive System": "2WD / 4WD Selectable",
      "Braking System": "Front & Rear Mechanical Disc",
      "Fuel Tank Capacity": "12 L",
      "Kerb Weight": "250 kg",
      "Max Load Capacity": "180 kg",
      "Ground Clearance": "220 mm",
    },
    features: ["300cc Engine","Panther Styling","2WD/4WD Selectable","Automatic Transmission","Disc Brakes All Round","Aggressive Tyres","Comfortable Riding Position","LED Headlights"],
    colors: ["Red","Gold","Green"],
    inStock: true,
    category: "ATV",
  },
  {
    id: "bike-5",
    name: "200cc Spark ATV",
    price: "₹2,45,000",
    shortDescription: "Entry-level 200cc Spark ATV — accessible off-road fun for beginners and enthusiasts alike.",
    fullDescription: "The 200cc Spark ATV is the perfect entry point into the exciting world of all-terrain vehicles. Its 200cc engine delivers approachable yet thrilling power that is ideal for beginners and intermediate riders. The Spark combines sporty styling with practical features like automatic transmission and selectable drive modes, making it incredibly easy to ride while still being capable enough for genuine off-road adventures. From weekend trail rides to farm utility work, the 200cc Spark ATV handles it all with ease.",
    images: [
      p("200cc-spark-atv", 1),
      p("200cc-spark-atv", 2),
      p("200cc-spark-atv", 3),
      p("200cc-spark-atv", 4),
      p("200cc-spark-atv", 5),
      p("200cc-spark-atv", 6),
      p("200cc-spark-atv", 7),
    ],
    specifications: {
      "Engine Type": "200cc, 4-Stroke, Air-Cooled",
      "Transmission": "Automatic (CVT)",
      "Drive System": "2WD Chain Drive",
      "Braking System": "Front & Rear Disc Brakes",
      "Fuel Tank Capacity": "10 L",
      "Kerb Weight": "200 kg",
      "Max Load Capacity": "150 kg",
      "Ground Clearance": "200 mm",
    },
    features: ["200cc Engine","Automatic Transmission","Beginner Friendly","Sporty Spark Design","Disc Brakes","Off-Road Tyres","Electric Start","Compact & Agile"],
    colors: ["Blue","Purple","Red"],
    inStock: true,
    category: "ATV",
  },
  {
    id: "bike-6",
    name: "50cc Neo Plus ATV",
    price: "₹45,000",
    shortDescription: "Compact 50cc Neo Plus ATV — safe, fun, and affordable off-road adventure for young riders.",
    fullDescription: "The 50cc Neo Plus ATV is designed specifically for young riders and beginners who want to experience the thrill of off-road riding in a safe and controlled manner. Its compact 50cc engine provides gentle yet exciting power, while the automatic transmission makes it effortless to operate. Built with safety in mind, it features speed limiters, responsive brakes, and a low seat height that gives young riders confidence. Available in multiple vibrant colors, the Neo Plus ATV is the perfect gift for adventurous kids and teens.",
    images: [
      p("50cc-neo-plus-atv", 1),
      p("50cc-neo-plus-atv", 2),
      p("50cc-neo-plus-atv", 3),
      p("50cc-neo-plus-atv", 4),
      p("50cc-neo-plus-atv", 5),
      p("50cc-neo-plus-atv", 6),
      p("50cc-neo-plus-atv", 7),
      p("50cc-neo-plus-atv", 8),
      p("50cc-neo-plus-atv", 9),
      p("50cc-neo-plus-atv", 10),
    ],
    specifications: {
      "Engine Type": "50cc, 2-Stroke, Air-Cooled",
      "Transmission": "Automatic",
      "Drive System": "2WD",
      "Braking System": "Front & Rear Disc Brakes",
      "Fuel Tank Capacity": "4 L",
      "Kerb Weight": "68 kg",
      "Max Load Capacity": "80 kg",
      "Ground Clearance": "150 mm",
      "Recommended Age": "8+ Years",
    },
    features: ["50cc Engine for Young Riders","Automatic Transmission","All Disc Brakes","Speed Limiter","Low Seat Height","Multiple Vibrant Colors","Electric Start","Remote Control Kill Switch"],
    colors: ["Orange","Blue","Gold","Pink","Red","Green"],
    inStock: true,
    category: "ATV",
  },
  {
    id: "bike-8",
    name: "125cc Pit Bike",
    price: "₹85,000",
    shortDescription: "Compact and powerful 125cc Pit Bike, combining trail capability with agile handling.",
    fullDescription: "The 125cc Pit Bike offers a smaller frame profile without sacrificing the raw, adrenaline-fueled power of a standard dirt bike. Excellent for backyard tracks, trail riding, and off-road practice. Built with a reinforced steel frame, heavy-duty suspension, manual clutch, and responsive wave disc brakes to conquer trails with absolute confidence.",
    images: [
      p("125cc-pit-bike", 1),
      p("125cc-pit-bike", 2),
      p("125cc-pit-bike", 3),
      p("125cc-pit-bike", 4),
      p("125cc-pit-bike", 5),
      p("125cc-pit-bike", 6),
      p("125cc-pit-bike", 7),
    ],
    specifications: {
      "Engine Type": "125cc, Single Cylinder, 4-Stroke, Air-Cooled",
      "Transmission": "4-Speed Manual Drivetrain",
      "Braking System": "Front & Rear Wave Disc Brakes",
      "Fuel Tank Capacity": "4.5 L",
      "Kerb Weight": "72 kg",
      "Max Load Capacity": "85 kg",
      "Ground Clearance": "260 mm",
      "Starter System": "Kick Start",
    },
    features: ["Compact Pit Bike Frame","Kick Start Engine","High-Grip Off-Road Tyres","Dual Wave Disc Brakes","Adjustable Rear Shock","Reinforced Swingarm"],
    colors: ["Green","Blue","Black"],
    inStock: true,
    category: "Dirt Bikes",
  },
  {
    id: "bike-9",
    name: "20 Inches Foldable Bicycle",
    price: "₹9,999",
    shortDescription: "Compact and lightweight 20-inch foldable bicycle — ultimate portability for daily urban commuters.",
    fullDescription: "The 20 Inches Foldable Bicycle is the perfect commuter companion. Its carbon steel folding frame is both rigid and incredibly easy to handle. With a 7-speed Shimano gear system, you can easily cruise up hills and navigate flat city pavement. Folds down in under 15 seconds to fit inside closets, office desks, or car trunks.",
    images: [
      p("20-inches-foldable-bicycle", 1),
      p("20-inches-foldable-bicycle", 2),
      p("20-inches-foldable-bicycle", 3),
      p("20-inches-foldable-bicycle", 4),
      p("20-inches-foldable-bicycle", 5),
      p("20-inches-foldable-bicycle", 6),
      p("20-inches-foldable-bicycle", 7),
      p("20-inches-foldable-bicycle", 8),
      p("20-inches-foldable-bicycle", 9),
      p("20-inches-foldable-bicycle", 10),
    ],
    specifications: {
      "Wheel Size": "20 Inches",
      "Frame Material": "Foldable Carbon Steel",
      "Braking System": "Front & Rear Alloy V-Brakes",
      "Gearbox": "7-Speed Shimano Gear System",
      "Kerb Weight": "12 kg",
      "Folded Dimensions": "65 x 50 x 30 cm",
      "Max Load Capacity": "95 kg",
      "Accessories": "Rear Carrier & Mudguards Included",
    },
    features: ["Ultra-Compact Folding Frame","7-Speed Shimano Gear System","Lightweight 12 kg","Adjustable Seat & Handlebar","Built-in Rear Carrier","Fenders Included"],
    colors: ["White","Black","Yellow"],
    inStock: true,
    category: "Bicycles",
  },
  {
    id: "bike-10",
    name: "20 Inches Foldable Fat Bicycle",
    price: "₹14,999",
    shortDescription: "20-inch foldable fat tyre bike — conquer urban streets, sand, and gravel with ease.",
    fullDescription: "The 20 Inches Foldable Fat Bicycle pairs the portability of a folding bike with the absolute traction of 4-inch wide tyres. This bicycle gives you the confidence to ride through mud, sand, snow, or loose gravel while folding down into a compact footprint when your ride is over.",
    images: [
      p("20-inches-foldable-fat-bicycle", 1),
      p("20-inches-foldable-fat-bicycle", 2),
      p("20-inches-foldable-fat-bicycle", 3),
      p("20-inches-foldable-fat-bicycle", 4),
      p("20-inches-foldable-fat-bicycle", 5),
    ],
    specifications: {
      "Wheel Size": "20\" Fat Tyre",
      "Frame Material": "High-Tensile Steel Foldable",
      "Braking System": "Front & Rear Mechanical Disc Brakes",
      "Gearbox": "7-Speed Shimano Gear System",
      "Kerb Weight": "14.5 kg",
      "Folded Dimensions": "70 x 55 x 35 cm",
      "Max Load Capacity": "100 kg",
      "Tyres Size": "20\" x 4.0\" Knobby Fat Tyres",
    },
    features: ["Quick Fold Mechanism","4.0\" Wide Fat Tyres for Mud/Snow","7-Speed Shimano Gears","Mechanical Disc Brakes","Sleek Urban Design"],
    colors: ["Black","Orange","White"],
    inStock: true,
    category: "Bicycles",
  },
  {
    id: "bike-11",
    name: "26 Inches Fat Tyre Jaguar Model Bicycle",
    price: "₹14,999",
    shortDescription: "Aggressive styling and 26-inch fat tyres make the Jaguar model the ultimate trail conqueror.",
    fullDescription: "The 26 Inches Fat Tyre Jaguar Model Bicycle features a unique, aerodynamic sporty steel frame and massive 4-inch fat tyres that provide unbeatable grip and shock absorption on rocky or loose trails. Fitted with high-end 21-speed Shimano gears, it handles climbs and fast descents with ease.",
    images: [
      p("26-inches-fat-tyre-jaguar-model-bicycle", 1),
      p("26-inches-fat-tyre-jaguar-model-bicycle", 2),
      p("26-inches-fat-tyre-jaguar-model-bicycle", 3),
      p("26-inches-fat-tyre-jaguar-model-bicycle", 4),
      p("26-inches-fat-tyre-jaguar-model-bicycle", 5),
      p("26-inches-fat-tyre-jaguar-model-bicycle", 6),
      p("26-inches-fat-tyre-jaguar-model-bicycle", 7),
      p("26-inches-fat-tyre-jaguar-model-bicycle", 8),
      p("26-inches-fat-tyre-jaguar-model-bicycle", 9),
    ],
    specifications: {
      "Wheel Size": "26\" Fat Tyre",
      "Frame Material": "Jaguar Sport Aero Steel Frame",
      "Braking System": "Dual Mechanical Disc Brakes",
      "Gearbox": "21-Speed Shimano System",
      "Suspension": "Front Suspension Fork",
      "Kerb Weight": "17 kg",
      "Max Load Capacity": "120 kg",
      "Tyres Size": "26\" x 4.0\" All-Terrain",
    },
    features: ["Aggressive Jaguar Styling Frame","21-Speed Shimano Drivetrain","Front Suspension Fork","Dual Mechanical Disc Brakes","All-Terrain Fat Tyres"],
    colors: ["Black/Red","White/Red","Blue/Black"],
    inStock: true,
    category: "Bicycles",
  },
  {
    id: "bike-12",
    name: "26 Inches Foldable Magwheel Fat Bicycle",
    price: "₹22,000",
    shortDescription: "High-end foldable fat bike featuring stylish 6-spoke magnesium alloy wheels.",
    fullDescription: "The 26 Inches Foldable Magwheel Fat Bicycle combines a folding alloy frame with striking 6-spoke magnesium alloy wheels. It offers the aggressive performance of 4-inch fat tyres, a full suspension system, and 21-speed Shimano gears, all while maintaining the ability to fold down for convenient storage.",
    images: [
      p("26-inches-foldable-magwheel-fat-bicycle", 1),
      p("26-inches-foldable-magwheel-fat-bicycle", 2),
      p("26-inches-foldable-magwheel-fat-bicycle", 3),
      p("26-inches-foldable-magwheel-fat-bicycle", 4),
      p("26-inches-foldable-magwheel-fat-bicycle", 5),
      p("26-inches-foldable-magwheel-fat-bicycle", 6),
      p("26-inches-foldable-magwheel-fat-bicycle", 7),
      p("26-inches-foldable-magwheel-fat-bicycle", 8),
    ],
    specifications: {
      "Wheel Size": "26\" Fat Tyre",
      "Frame Material": "Foldable Alloy Frame",
      "Braking System": "Front & Rear Mechanical Disc Brakes",
      "Gearbox": "21-Speed Shimano Gearset",
      "Wheels Type": "6-Spoke Magnesium Alloy Mag Wheels",
      "Kerb Weight": "16.5 kg",
      "Max Load Capacity": "115 kg",
      "Suspension": "Dual Suspension (Front Fork & Rear Spring)",
    },
    features: ["Premium Magnesium Alloy Wheels","Quick Fold Space-Saving Frame","21-Speed Shimano Drivetrain","Dual Mechanical Disc Brakes","Front Suspension System"],
    colors: ["Yellow","White","Black"],
    inStock: true,
    category: "Bicycles",
  },
  {
    id: "bike-13",
    name: "36 Volts Drifter Electric Trike",
    price: "₹22,000",
    shortDescription: "36V rechargeable electric drifting trike — execute thrilling 360° spins with ease.",
    fullDescription: "Unleash extreme fun with the 36 Volts Drifter Electric Trike. Powered by a 250W hub motor and a long-lasting lithium battery, this drift machine allows children and teens to zoom, spin, and slide. Dual inclined rear casters enable 360-degree drifting action, while integrated LED lights and built-in Bluetooth speakers add high-tech style to every spin.",
    images: [
      p("36-volts-drifter", 1),
      p("36-volts-drifter", 2),
      p("36-volts-drifter", 3),
      p("36-volts-drifter", 4),
      p("36-volts-drifter", 5),
      p("36-volts-drifter", 6),
    ],
    specifications: {
      "Battery System": "36V Lithium-ion Rechargeable",
      "Motor Power": "250W Brushless Front Hub Motor",
      "Frame Construction": "Heavy-Duty Welded Steel",
      "Braking": "Front Hand-Operated Caliper Brake",
      "Continuous Run Time": "Up to 45 minutes per charge",
      "Max Speed": "15 km/h",
      "Weight Capacity": "65 kg",
      "Rear Wheels": "Dual Inclined Casters for Drifting",
    },
    features: ["360-Degree Spinning & Drifting","Pneumatic Front Tyre","Dual Inclined Rear Caster Wheels","3-Speed Throttle Control","Vibrant LED Safety Lights","Bluetooth Speakers built-in"],
    colors: ["Blue Camo","Red Flame","Graffiti"],
    inStock: true,
    category: "Hoverboards & Drifters",
  },
  {
    id: "bike-14",
    name: "50cc Dirt Bike",
    price: "₹26,000",
    shortDescription: "Perfect starter 50cc 2-stroke dirt bike for young riders. Lightweight, safe, and fun.",
    fullDescription: "The 50cc Dirt Bike is the ultimate starter machine for kids. Equipped with a simple automatic 'twist-and-go' throttle, a safety kill switch lanyard, and full mechanical disc brakes. The lightweight steel frame and front/rear suspension ensure a comfortable and thrilling introduction to off-road riding.",
    images: [
      p("50cc-dirt-bike", 1),
      p("50cc-dirt-bike", 2),
      p("50cc-dirt-bike", 3),
      p("50cc-dirt-bike", 4),
      p("50cc-dirt-bike", 5),
      p("50cc-dirt-bike", 6),
      p("50cc-dirt-bike", 7),
    ],
    specifications: {
      "Engine Type": "50cc, Single Cylinder, 2-Stroke, Air-Cooled",
      "Transmission": "Single-Speed Automatic (Centrifugal Clutch)",
      "Braking System": "Front & Rear Mechanical Disc Brakes",
      "Fuel Capacity": "2 L (Petrol + 2-Stroke Oil Mix)",
      "Kerb Weight": "24 kg",
      "Max Load Capacity": "60 kg",
      "Suspension": "Front Telescopic Fork, Rear Mono Shock",
      "Starter System": "Easy Pull-Start System",
    },
    features: ["Vibrant Kids Dirt Bike Styling","Automatic Twist-and-Go Throttle","Tether Safety Kill Switch","Lightweight 24 kg frame","Heavy Duty Disc Brakes","Responsive Front and Rear Suspension"],
    colors: ["Green","Orange","Red","Blue"],
    inStock: true,
    category: "Dirt Bikes",
  },
  {
    id: "bike-15",
    name: "6.5 Inches Hoverboard",
    price: "₹9,999",
    shortDescription: "Sleek 6.5-inch self-balancing hoverboard with built-in Bluetooth speakers and LED arch lights.",
    fullDescription: "The 6.5 Inches Hoverboard is packed with modern features, featuring a self-balancing gyroscope system that makes it highly intuitive for beginners. Powered by dual 250W motors, it cruises smoothly on flat terrain. It includes integrated Bluetooth speakers, vibrant LED arch lighting on wheels, and a UL2272 safety-certified lithium battery.",
    images: [
      p("6.5-inches-havour-board", 1),
      p("6.5-inches-havour-board", 2),
      p("6.5-inches-havour-board", 3),
      p("6.5-inches-havour-board", 4),
      p("6.5-inches-havour-board", 5),
      p("6.5-inches-havour-board", 6),
    ],
    specifications: {
      "Wheel Diameter": "6.5 Inches Solid Rubber",
      "Battery System": "36V Lithium-ion UL2272 Certified",
      "Motor Configuration": "Dual 250W Brushless Hub Motors",
      "Max Riding Speed": "12 km/h",
      "Travel Range": "10-12 km per charge",
      "Charging Time": "Approx. 2 Hours",
      "Max Load Capacity": "80 kg",
      "Gyroscopic Sensor": "Built-in Self-Balancing System",
    },
    features: ["High-Tech Self-Balancing System","Vibrant LED Arch Lights on Wheels","Built-in Bluetooth Speaker","Non-slip Rubber Footpads","UL2272 Safety Certified Battery"],
    colors: ["Chrome Pink","Chrome Blue","Chrome Silver","Matte Black"],
    inStock: true,
    category: "Hoverboards & Drifters",
  },
  {
    id: "bike-16",
    name: "8 Inches Hoverboard",
    price: "₹12,999",
    shortDescription: "Rugged 8-inch off-road styled self-balancing hoverboard with wide stable tyres.",
    fullDescription: "The 8 Inches Hoverboard is designed for riders looking for extra stability. With its larger 8-inch solid rubber tyres and aggressive shell design, it handles cracks, bumps, and light gravel paths with ease. Includes built-in Bluetooth speakers, running LED path lights, and self-balancing gyroscopic sensors.",
    images: [
      p("8-inches-havour-board", 1),
      p("8-inches-havour-board", 2),
      p("8-inches-havour-board", 3),
      p("8-inches-havour-board", 4),
      p("8-inches-havour-board", 5),
    ],
    specifications: {
      "Wheel Diameter": "8 Inches Solid Rubber",
      "Battery System": "36V Lithium-ion UL2272 Certified",
      "Motor Configuration": "Dual 300W Brushless Hub Motors",
      "Max Riding Speed": "15 km/h",
      "Travel Range": "12-15 km per charge",
      "Charging Time": "Approx. 2.5 Hours",
      "Max Load Capacity": "100 kg",
      "Gyroscopic Sensor": "Built-in Self-Balancing System",
    },
    features: ["Large 8-inch Wheels for Stable Ride","Off-Road Styled Shell","Built-in Bluetooth Speakers","Dynamic Running LED Lights","Rugged Non-slip Pedals"],
    colors: ["Red Flame","Blue Camo","Graffiti Black"],
    inStock: true,
    category: "Hoverboards & Drifters",
  },
  {
    id: "bike-17",
    name: "250cc Super Hunk ATV",
    price: "₹2,75,000",
    shortDescription: "Massive 250cc Super Hunk ATV with winch, backrest, outer cage, and extra tyre — ultimate off-road power.",
    fullDescription: "The 250cc Super Hunk ATV is a high-capacity all-terrain vehicle designed for extreme off-road terrains. Powered by a heavy-duty 250cc 4-stroke oil-cooled engine and featuring a 3-speed transmission with reverse, it offers unparalleled muscle and control. Standard equipped with a front electric winch, rugged backrest, protective outer cage, powerful LED spotlights, and a rear-mounted extra tyre, it is fully loaded for any adventure.",
    images: [
      p("250cc-super-hunk-atv", 1),
      p("250cc-super-hunk-atv", 2),
      p("250cc-super-hunk-atv", 3),
      p("250cc-super-hunk-atv", 4),
    ],
    specifications: {
      "Engine Type": "250cc, 4-Stroke, Single Cylinder, Oil-Cooled",
      "Max Power": "12 kW @ 6500 rpm",
      "Starter System": "Electric Start & Pull Start",
      "Transmission": "3-Speed with Reverse (1F+1N+1R)",
      "Clutch": "Automatic",
      "Braking System": "Front & Rear All Hydraulic Disc Brakes",
      "Suspension": "Hydraulic Suspension",
      "Tyres": "25x8-10 (Front) / 25x10-10 (Rear) with Aluminum Rims",
      "Fuel Capacity": "8.5 L",
      "Max Speed": "80 km/h",
      "Max Load Capacity": "200 kg",
    },
    features: ["Front Electric Winch","Protective Outer Cage","4x High-Power Carrier Spotlights","Rear Passenger Backrest","Rear-Mounted Full Extra Tyre","Digital Speedometer","Dual Hydraulic Disc Brakes"],
    colors: ["Yellow","Camo Green","Black"],
    inStock: true,
    category: "ATV",
  },
  {
    id: "bike-18",
    name: "135cc Neoplus ATV",
    price: "₹1,10,000",
    shortDescription: "Sleek and agile 135cc Neoplus ATV with backrest, digital speedometer, and remote start.",
    fullDescription: "The 135cc Neoplus ATV offers a fantastic balance of off-road agility and robust performance. Designed with rider convenience in mind, it comes equipped with a digital speedometer, handguards, a comfortable rear backrest, a remote kill/start key, and bright LED headlamps with dual extra spotlights to illuminate the dark trails.",
    images: [
      p("135cc-neoplus-atv", 1),
      p("135cc-neoplus-atv", 2),
      p("135cc-neoplus-atv", 3),
      p("135cc-neoplus-atv", 4),
      p("135cc-neoplus-atv", 5),
    ],
    specifications: {
      "Engine Type": "135cc, 4-Stroke, Single Cylinder, Air-Cooled",
      "Starter System": "Electric Start with Remote Control",
      "Braking System": "Front Drum & Rear Hydraulic Disc Brakes",
      "Absorbers": "Dual Front & Single Rear Hydraulic Shock Absorbers",
      "Tires": "Front 19x7-8 / Rear 18x9.5-8",
      "Transmission": "3-Speed with Reverse (1F+1N+1R)",
      "Fuel Capacity": "4.5 L",
      "Max Speed": "45 km/h",
      "Max Load Capacity": "150 kg",
    },
    features: ["Rear Backrest and Handguards","Digital Speedometer Console","Remote Start/Stop System","High-Power LED Lighting","Dual Front Spotlights","Colorful Rim Covers"],
    colors: ["Red","Blue","Black","White"],
    inStock: true,
    category: "ATV",
  },
  {
    id: "bike-19",
    name: "50cc Mini ATV",
    price: "₹45,000",
    shortDescription: "Vibrant 50cc Mini Neo ATV with a 2-stroke petrol engine, automatic transmission, and all disc brakes.",
    fullDescription: "The 50cc Mini Neo ATV is the perfect junior machine for young riders. Sporting a reliable 49cc 2-stroke single cylinder air-cooled engine and a fully automatic transmission, it is extremely easy and fun to handle. Front and rear disc brakes and spring absorbers ensure a secure and stable ride.",
    images: [
      p("50cc-mini-atv", 1),
      p("50cc-mini-atv", 2),
      p("50cc-mini-atv", 3),
      p("50cc-mini-atv", 4),
      p("50cc-mini-atv", 5),
      p("50cc-mini-atv", 6),
      p("50cc-mini-atv", 7),
    ],
    specifications: {
      "Engine Type": "49cc, Single Cylinder, 2-Stroke, Air-Cooled",
      "Starter System": "Pull Start + Self Start",
      "Max Torque": "3.5 N.m @ 6000 rpm",
      "Braking System": "Front & Rear Mechanical Disc Brakes",
      "Suspension": "Front & Rear Dual Spring Absorbers",
      "Tyres": "4.10-6 (Front) / 13x5.00-6 (Rear)",
      "Drive Train": "Chain Drive",
      "Fuel Capacity": "1 L",
      "Dimensions": "1050 x 580 x 470 mm",
      "Seat Height": "530 mm",
      "Max Speed": "45 km/h",
      "Max Load Capacity": "110 kg",
    },
    features: ["Junior Rider Dimensions","Easy Automatic Transmission","Electric Key Start & Pull Start","Front and Rear Cargo Racks","Dual Disc Brakes","Safety Lanyard Kill Switch"],
    colors: ["Orange","Black","Blue","Green","Red"],
    inStock: true,
    category: "ATV",
  },
  {
    id: "bike-20",
    name: "50cc Mini Mouzer ATV",
    price: "₹45,000",
    shortDescription: "A sporty junior 50cc Mini Mouzer ATV with aggressive utility racks and automatic performance.",
    fullDescription: "The 50cc Mini Mouzer ATV is designed for kids and teens who want an aggressive off-road look. With front and rear carrier grids, high-performance disc brakes, and automatic twist-and-go acceleration, it offers thrilling yet approachable trail action.",
    images: [
      p("50cc-mini-mouzer-atv", 1),
      p("50cc-mini-mouzer-atv", 2),
      p("50cc-mini-mouzer-atv", 3),
      p("50cc-mini-mouzer-atv", 4),
      p("50cc-mini-mouzer-atv", 5),
    ],
    specifications: {
      "Engine Type": "49cc, Single Cylinder, 2-Stroke, Air-Cooled",
      "Starter System": "Pull Start + Self Start",
      "Braking System": "Front & Rear Disc Brakes",
      "Suspension": "Dual Front & Single Rear Spring Absorber",
      "Tyres": "4.10-6 (Front) / 13x5.00-6 (Rear)",
      "Drive Train": "Chain Drive",
      "Fuel Capacity": "1 L",
      "Max Speed": "45 km/h",
      "Max Load Capacity": "110 kg",
    },
    features: ["Aggressive Mouzer Body Panels","Automatic Centrifugal Clutch","Key Switch & Pull Starter","Front & Rear Utility Racks","Non-slip Footwells","Vibrant Accent Rims"],
    colors: ["Black","Red","Blue","White"],
    inStock: true,
    category: "ATV",
  },
  {
    id: "bike-21",
    name: "135cc Phantom ATV",
    price: "₹1,10,000",
    shortDescription: "Aggressive 135cc Phantom ATV with camo decals, handguards, backrest, and spotlight system.",
    fullDescription: "The 135cc Phantom ATV is built for conquering complex off-road terrains. Featuring a durable 135cc 4-stroke automatic engine and full utility fixtures, it comes equipped with handguards, a rearview mirror, backrest, digital speedometer, and high-visibility LED spotlights.",
    images: [
      p("135cc-phantom-atv", 1),
      p("135cc-phantom-atv", 2),
      p("135cc-phantom-atv", 3),
      p("135cc-phantom-atv", 4),
      p("135cc-phantom-atv", 5),
      p("135cc-phantom-atv", 6),
      p("135cc-phantom-atv", 7),
    ],
    specifications: {
      "Engine Type": "135cc, 4-Stroke, Single Cylinder, Air-Cooled",
      "Max Power": "5.8 kW @ 5000 rpm",
      "Starter System": "Electric Start",
      "Transmission": "3-Speed with Reverse (1F+1N+1R)",
      "Clutch": "Automatic",
      "Braking System": "Front Drum & Rear Hydraulic Disc Brakes",
      "Suspension": "All Hydraulic Shock Absorbers",
      "Tyres": "Front 19x7-8 / Rear 18x9.5-8",
      "Fuel Capacity": "4.5 L",
      "Seat Height": "80 cm",
      "Max Speed": "45 km/h",
      "Max Load Capacity": "150 kg",
    },
    features: ["Aggressive Camo & Sport Styling","Protective Handguards & Mirrors","Digital Speedometer","Passenger Backrest","Electric Start Key & Remote","Heavy Duty Hydraulic Dampeners"],
    colors: ["Camo Green","White","Blue","Yellow","Red","Black"],
    inStock: true,
    category: "ATV",
  },
  {
    id: "bike-22",
    name: "500cc Beast ATV",
    price: "₹4,80,000",
    shortDescription: "Rugged and aggressive 500cc Beast ATV with 4x4 drive, speed limiters, and dual racks.",
    fullDescription: "The 500cc Beast ATV is designed for ultimate off-road power and capability. Equipped with a robust 500cc 4-stroke petrol engine and selectable 4x4 system, it easily tackles steep hills, muddy tracks, and rocky fields. Features heavy-duty front and rear utility racks, automatic CVT transmission with reverse, a comfortable passenger backrest, and high-performance SUNF off-road tires for maximum grip.",
    images: [
      "./public/products/500cc-beast-atv-p1.jpg",
      "./public/products/500cc-beast-atv-p2.jpg",
      "./public/products/500cc-beast-atv-p3.jpg",
      "./public/products/500cc-beast-atv-p4.jpg",
      "./public/products/500cc-beast-atv-p5.jpg",
      "./public/products/500cc-beast-atv-p6.jpg",
      "./public/products/500cc-beast-atv-p7.jpg",
      "./public/products/500cc-beast-atv-p8.jpg",
      "./public/products/500cc-beast-atv-p9.jpg",
    ],
    specifications: {
      "Engine Type": "500cc, Single Cylinder, 4-Stroke, Air-Cooled",
      "Transmission": "Automatic CVT (F-N-R)",
      "Drive System": "4WD / 2WD Selectable",
      "Braking System": "Front & Rear Hydraulic Disc Brakes",
      "Fuel Tank Capacity": "14 L",
      "Kerb Weight": "295 kg",
      "Max Load Capacity": "190 kg",
      "Tyres": "SUNF All-Terrain Tubeless",
    },
    features: ["Powerful 500cc Engine","Selectable 4WD Drive","Front & Rear Utility Racks","CVT Automatic Gearbox","Comfortable Passenger Backrest","SUNF Off-Road Heavy Duty Tires","Dual Speed Modes","Electric Key Start"],
    colors: ["Grey","Silver"],
    inStock: true,
    category: "ATV",
  },
  {
    id: "bike-23",
    name: "200cc Side-by-Side UTV",
    price: "₹3,50,000",
    shortDescription: "Premium 200cc Side-by-Side UTV with roll cage, passenger seats, and canopy.",
    fullDescription: "The 200cc Side-by-Side UTV brings the comfort of double seating and roll-cage safety to your off-road adventures. Powered by a dependable 200cc 4-stroke air-cooled engine with automatic transmission (1 Forward + 1 Reverse), it features a sturdy canopy roof, rear storage cargo bed, dual bucket seats with safety belts, and a full steel tube roll cage. Perfect for farm utility work or weekend recreation.",
    images: [
      "./public/products/200cc-utv-p1.jpg",
      "./public/products/200cc-utv-p2.jpg",
      "./public/products/200cc-utv-p3.jpg",
      "./public/products/200cc-utv-p4.jpg",
    ],
    specifications: {
      "Engine Type": "200cc, Single Cylinder, 4-Stroke, Air-Cooled",
      "Transmission": "Automatic CVT with Reverse (1F+1R)",
      "Drive System": "2WD Chain Drive",
      "Braking System": "Front & Rear Hydraulic Disc Brakes",
      "Fuel Tank Capacity": "9.5 L",
      "Kerb Weight": "240 kg",
      "Max Load Capacity": "180 kg",
      "Seats": "Dual Bucket Seats with Safety Belts",
    },
    features: ["Two-Seater Side-by-Side Design","Full Steel Roll Cage","Protective Canopy Roof","Rear Cargo Storage Box","Automatic Transmission","Dual Hydraulic Disc Brakes","All-Terrain Utility Tires"],
    colors: ["Blue","Black"],
    inStock: true,
    category: "ATV",
  },
  {
    id: "bike-24",
    name: "200cc Super Bull ATV",
    price: "₹2,50,000",
    shortDescription: "Aggressive 200cc Super Bull ATV featuring front winch, spare tire, and outer safety cage.",
    fullDescription: "The 200cc Super Bull ATV is a fully loaded quad bike built for serious trail work and emergency rescue styling. It features a front electric winch, a passenger backrest, a protective outer safety cage, high-intensity LED headlights, side mirrors, and a rear-mounted extra tire. Powered by a reliable 200cc engine, it supports electric self-start, kick start, and remote start capabilities.",
    images: [
      "./public/products/200cc-super-bull-atv-p1.jpg",
      "./public/products/200cc-super-bull-atv-p2.jpg",
      "./public/products/200cc-super-bull-atv-p3.jpg",
      "./public/products/200cc-super-bull-atv-p4.jpg",
      "./public/products/200cc-super-bull-atv-p5.jpg",
    ],
    specifications: {
      "Engine Type": "200cc, Single Cylinder, 4-Stroke, Air-Cooled",
      "Starter System": "Electric Key Start + Pull Start + Remote Control",
      "Transmission": "Automatic with Reverse",
      "Braking System": "Front Drum & Rear Hydraulic Disc Brakes",
      "Fuel Tank Capacity": "8 L",
      "Kerb Weight": "210 kg",
      "Max Load Capacity": "150 kg",
      "Accessories": "Front Winch, Rear Extra Tire, Side Mirrors",
    },
    features: ["Heavy-Duty Front Electric Winch","Rear-Mounted Full-Size Spare Tire","Protective Outer Safety Cage","Remote Start/Stop Key","High-Intensity LED Lighting System","Rear Passenger Backrest & Handguards"],
    colors: ["Blue","Black"],
    inStock: true,
    category: "ATV",
  },
  {
    id: "bike-25",
    name: "150cc Mini Jeep",
    price: "₹2,20,000",
    shortDescription: "Classic military-styled 150cc Mini Jeep with manual transmission, spare tire, and jerry can.",
    fullDescription: "The 150cc Mini Jeep is a recreation of the classic military style vehicle in a compact size. Powered by a 150cc 4-stroke petrol engine with a 3-speed manual transmission plus reverse (3-2-1-N-R), it delivers authentic driving dynamics. Standard features include a folding windshield, double padded seats, headlights, rear-mounted spare tire, and a decorative jerry can.",
    images: [
      "./public/products/150cc-mini-jeep-p1.jpg",
      "./public/products/150cc-mini-jeep-p2.jpg",
      "./public/products/150cc-mini-jeep-p3.jpg",
      "./public/products/150cc-mini-jeep-p4.jpg",
      "./public/products/150cc-mini-jeep-p5.jpg",
      "./public/products/150cc-mini-jeep-p6.jpg",
      "./public/products/150cc-mini-jeep-p7.jpg",
      "./public/products/150cc-mini-jeep-p8.jpg",
      "./public/products/150cc-mini-jeep-p9.jpg",
    ],
    specifications: {
      "Engine Type": "150cc, Single Cylinder, 4-Stroke, Air-Cooled",
      "Transmission": "3-Speed Manual Drivetrain with Reverse",
      "Starter System": "Electric Key Start",
      "Braking System": "Front & Rear Hydraulic Disc Brakes",
      "Fuel Tank Capacity": "7 L",
      "Kerb Weight": "180 kg",
      "Max Load Capacity": "140 kg",
      "Accessories": "Spare Tire, Fuel Jerry Can, Foldable Windshield",
    },
    features: ["Classic US Army Military Design","3-Speed Manual with Reverse Drivetrain","Folding Windshield & Side Mirrors","Rear-Mounted Spare Wheel & Jerry Can","Comfortable Dual Seating","Hydraulic Disc Brakes Front & Rear"],
    colors: ["Army Green"],
    inStock: true,
    category: "ATV",
  },
  {
    id: "bike-26",
    name: "Super Motocross 125cc",
    price: "₹75,000",
    shortDescription: "Aggressive 125cc dirt bike with red anodized forks, heavy duty cradle frame, and manual clutch.",
    fullDescription: "The Super Motocross 125cc is a pure off-road trail machine designed for high jumps and high speed. Featuring a robust 125cc 4-stroke engine, manual 4-speed clutch, anodized red front forks and matching rims, and wave-style dual disc brakes. The reinforced cradle steel frame and heavy-duty suspension absorb the toughest terrain jumps.",
    images: [
      "./public/products/super-motocross-125cc-p1.jpg",
      "./public/products/super-motocross-125cc-p2.jpg",
      "./public/products/super-motocross-125cc-p3.jpg",
      "./public/products/super-motocross-125cc-p4.jpg",
      "./public/products/super-motocross-125cc-p5.jpg",
      "./public/products/super-motocross-125cc-p6.jpg",
    ],
    specifications: {
      "Engine Type": "125cc, Single Cylinder, 4-Stroke, Air-Cooled",
      "Transmission": "4-Speed Manual Gearbox",
      "Suspension": "Upside Down Front Forks, Heavy Duty Rear Mono Shock",
      "Braking System": "Front & Rear Wave Disc Brakes",
      "Fuel Tank Capacity": "4.5 L",
      "Kerb Weight": "73 kg",
      "Max Load Capacity": "95 kg",
      "Tires": "17\" Front, 14\" Rear Off-Road Knobby",
    },
    features: ["High-End Anodized Red Suspension & Rims","4-Speed Manual Gear Drivetrain","Reinforced Steel Cradle Frame","High-Grip Knobby Off-Road Tyres","Wave Disc Brakes Front & Rear","Kick & Electric Self Start"],
    colors: ["Black","Red"],
    inStock: true,
    category: "Dirt Bikes",
  },
  {
    id: "bike-27",
    name: "135cc Super Phantom ATV",
    price: "₹1,20,000",
    shortDescription: "Premium 135cc Super Phantom ATV with aluminum rims, backrest, handguards, and digital console.",
    fullDescription: "The 135cc Super Phantom ATV is an upgraded, high-spec utility quad. Featuring a powerful 135cc 4-stroke engine, striking aluminum alloy wheels, passenger backrest, protective outer brush guards, handguards, and a digital console display. Equipped with remote control key start/stop and bright LED projector headlamps with extra spotlights.",
    images: [
      "./public/products/135cc-super-phantom-atv-p1.jpg",
      "./public/products/135cc-super-phantom-atv-p2.jpg",
      "./public/products/135cc-super-phantom-atv-p3.jpg",
      "./public/products/135cc-super-phantom-atv-p4.jpg",
      "./public/products/135cc-super-phantom-atv-p5.jpg",
      "./public/products/135cc-super-phantom-atv-p6.jpg",
      "./public/products/135cc-super-phantom-atv-p7.jpg",
    ],
    specifications: {
      "Engine Type": "135cc, Single Cylinder, 4-Stroke, Air-Cooled",
      "Starter System": "Electric Start with Remote Control",
      "Transmission": "Automatic with Reverse (F-N-R)",
      "Braking System": "Front Drum & Rear Hydraulic Disc Brakes",
      "Wheels": "Premium Aluminum Alloy Wheels",
      "Fuel Tank Capacity": "5 L",
      "Kerb Weight": "165 kg",
      "Max Load Capacity": "145 kg",
    },
    features: ["Striking Aluminum Alloy Wheels","Digital Speedometer Display","Rear Passenger Backrest & Handguards","Dual Spotlight Pods + LED Headlights","Remote Start/Stop System","Sturdy Front & Rear Utility Grids"],
    colors: ["Yellow","Black"],
    inStock: true,
    category: "ATV",
  },
  {
    id: "bike-28",
    name: "Motocross Pro 125cc",
    price: "₹80,000",
    shortDescription: "Feature-packed 125cc Motocross Pro dirt bike with headlight, manual transmission, and high-clearance frame.",
    fullDescription: "The Motocross Pro 125cc is a professional-grade trail dirt bike equipped for night and day adventure. Featuring an integrated front headlight, a 125cc 4-stroke engine, a 4-speed manual gearbox, dual hydraulic disc brakes, and high-tensile steel cradle construction. Its long-travel suspension delivers superior shock absorption on dirt jumps.",
    images: [
      "./public/products/motocross-pro-125cc-p1.jpg",
      "./public/products/motocross-pro-125cc-p2.jpg",
      "./public/products/motocross-pro-125cc-p3.jpg",
      "./public/products/motocross-pro-125cc-p4.jpg",
    ],
    specifications: {
      "Engine Type": "125cc, Single Cylinder, 4-Stroke, Air-Cooled",
      "Transmission": "4-Speed Manual Clutch (1-N-2-3-4)",
      "Braking System": "Front & Rear Hydraulic Disc Brakes",
      "Suspension": "Long-Travel Hydraulic Forks & Rear Shock",
      "Fuel Tank Capacity": "5.2 L",
      "Kerb Weight": "76 kg",
      "Max Load Capacity": "90 kg",
      "Lighting": "Front Halogen Headlight",
    },
    features: ["Integrated Front Headlight for Night Riding","4-Speed Manual Transmission","High Ground Clearance Frame","Dual Hydraulic Wave Disc Brakes","High-Traction Knobby Dirt Tyres","Electric Key Start & Kick Start"],
    colors: ["White","Orange","Blue"],
    inStock: true,
    category: "Dirt Bikes",
  },
  {
    id: "bike-29",
    name: "Dirt Plus 50cc",
    price: "₹32,000",
    shortDescription: "Junior 50cc Dirt Plus bike with automatic transmission, pull start, and vibrant lime green spokes.",
    fullDescription: "The Dirt Plus 50cc is the ideal first dirt bike for younger riders. Equipped with a reliable 50cc 2-stroke petrol engine, a simple fully automatic twist-and-go transmission, front/rear disc brakes, and a remote safety kill switch. Eye-catching lime green matching frame and wheel spokes give it a professional racer look.",
    images: [
      "./public/products/dirt-plus-50cc-p1.jpg",
      "./public/products/dirt-plus-50cc-p2.jpg",
      "./public/products/dirt-plus-50cc-p3.jpg",
      "./public/products/dirt-plus-50cc-p4.jpg",
      "./public/products/dirt-plus-50cc-p5.jpg",
      "./public/products/dirt-plus-50cc-p6.jpg",
    ],
    specifications: {
      "Engine Type": "50cc, Single Cylinder, 2-Stroke, Air-Cooled",
      "Transmission": "Automatic (Centrifugal Clutch)",
      "Starter System": "Easy Pull-Start + Electric Self-Start",
      "Braking System": "Front & Rear Mechanical Disc Brakes",
      "Fuel Tank Capacity": "2 L",
      "Kerb Weight": "26 kg",
      "Max Load Capacity": "55 kg",
      "Safety": "Lanyard Latch Kill Switch",
    },
    features: ["Vibrant Racer Styling with Lime Green Frame","Simple Automatic Twist-and-Go Operation","Dual Mechanical Disc Brakes","Front Telescopic Fork & Rear Shock","Safety Lanyard Latch Shutoff","Lightweight, Beginner-Friendly Frame"],
    colors: ["Green","White","Black"],
    inStock: true,
    category: "Dirt Bikes",
  },
  {
    id: "bike-30",
    name: "125cc Monkey Bike",
    price: "₹90,000",
    shortDescription: "Classic vintage-style 125cc Monkey Bike with high handlebars, side mirrors, and semi-automatic transmission.",
    fullDescription: "The 125cc Monkey Bike recreates the vintage mini-motorcycle design with modern performance. Equipped with high-rise chrome handlebars, dual side mirrors, a full headlight and tail light kit, front and rear disc brakes, and a semi-automatic 4-speed transmission that doesn't require a manual clutch lever, making it incredibly fun and easy to cruise around.",
    images: [
      "./public/products/125cc-monkey-bike-p1.jpg",
      "./public/products/125cc-monkey-bike-p2.jpg",
      "./public/products/125cc-monkey-bike-p3.jpg",
      "./public/products/125cc-monkey-bike-p4.jpg",
      "./public/products/125cc-monkey-bike-p5.jpg",
    ],
    specifications: {
      "Engine Type": "125cc, Single Cylinder, 4-Stroke, Air-Cooled",
      "Transmission": "4-Speed Semi-Automatic",
      "Starter System": "Electric Self-Start + Kick Start Backup",
      "Braking System": "Front & Rear Hydraulic Disc Brakes",
      "Lighting": "Headlight, Turn Indicators & Taillight",
      "Fuel Tank Capacity": "4.5 L",
      "Kerb Weight": "68 kg",
      "Max Load Capacity": "85 kg",
    },
    features: ["Vintage Retro Mini Motorcycle Design","4-Speed Semi-Automatic Gearbox (No Clutch Lever)","High-Rise Chrome Handlebars","Full Road-Legal Style Lighting & Indicators","Chrome Side Mirrors & Fender Trims","Hydraulic Disc Brakes Front & Rear"],
    colors: ["Red"],
    inStock: true,
    category: "Dirt Bikes",
  },
];

const heroImages = [
  "./public/products/125cc-monkey-bike-p1.jpg",
  "./public/products/dirt-plus-50cc-p1.jpg",
  "./public/products/super-motocross-125cc-p1.jpg"
];

const categories = [
  "All",
  "ATV",
  "Bicycles",
  "Dirt Bikes",
  "Hoverboards & Drifters"
];
