const p = (slug, page) => `./public/products/${slug}-p${page}.png`;

const bikesData = [
  {
    id: "bike-20",
    name: "MINI MOUZER ATV",
    price: "₹45,000",
    shortDescription: "Sporty 50cc Mini Mouzer ATV with a 2-stroke petrol engine, automatic transmission, and all disc brakes.",
    fullDescription: "The 50cc Mini Mouzer ATV is designed for kids and teens who want an aggressive off-road look. With front and rear carrier grids, high-performance disc brakes, and automatic twist-and-go acceleration, it offers thrilling yet approachable trail action.",
    images: [
      p("50cc-mini-mouzer-atv", 1),
      p("50cc-mini-mouzer-atv", 2),
      p("50cc-mini-mouzer-atv", 3),
      p("50cc-mini-mouzer-atv", 4),
      p("50cc-mini-mouzer-atv", 5),
    ],
    specifications: {
      "Engine Type": "49cc, Single Cylinder, 2-Stroke, Air-Cooled",
      "Transmission": "Automatic",
      "Starter System": "Self Start + Pull Start",
      "Braking System": "Front & Rear Disc Brakes",
      "Suspension": "Dual Front & Single Rear Spring Absorber",
      "Tyres": "4.10-6 (Front) / 13x5.00-6 (Rear)",
      "Drive Train": "Chain Drive",
      "Fuel Capacity": "1 L",
      "Seat Height": "530 mm",
      "Max Speed": "45 km/h",
      "Max Load Capacity": "110 kg",
    },
    features: ["Aggressive Mouzer Body Panels","Automatic Centrifugal Clutch","Key Switch & Pull Starter","Front & Rear Utility Racks","Non-slip Footwells","Vibrant Accent Rims"],
    colors: ["Black","Red","Blue","White"],
    inStock: true,
    category: "ATV",
  },
  {
    id: "bike-14",
    name: "DIRT BIKE",
    price: "₹26,000",
    shortDescription: "Starter 50cc 2-stroke dirt bike with automatic transmission, self start + pull start, and all disc brakes.",
    fullDescription: "The 50cc Dirt Bike is the ultimate starter machine for kids. Equipped with a simple automatic 'twist-and-go' throttle, self start + pull start, a safety kill switch lanyard, and full mechanical disc brakes. The lightweight steel frame and front/rear suspension ensure a comfortable and thrilling introduction to off-road riding.",
    images: [
      p("50cc-dirt-bike", 1),
      p("50cc-dirt-bike", 2),
      p("50cc-dirt-bike", 3),
      p("50cc-dirt-bike", 4),
      p("50cc-dirt-bike", 5),
      p("50cc-dirt-bike", 6),
      p("50cc-dirt-bike", 7),
    ],
    specifications: {
      "Engine Type": "50cc, Single Cylinder, 2-Stroke, Air-Cooled",
      "Transmission": "Single-Speed Automatic (Centrifugal Clutch)",
      "Starter System": "Self Start + Pull Start",
      "Braking System": "Front & Rear Mechanical Disc Brakes",
      "Fuel Capacity": "2 L (Petrol + 2-Stroke Oil Mix)",
      "Kerb Weight": "24 kg",
      "Max Load Capacity": "60 kg",
      "Suspension": "Front Telescopic Fork, Rear Mono Shock",
    },
    features: ["Vibrant Kids Dirt Bike Styling","Automatic Twist-and-Go Throttle","Tether Safety Kill Switch","Lightweight 24 kg frame","Heavy Duty Disc Brakes","Responsive Front and Rear Suspension"],
    colors: ["Black","Green","Orange","Red","White","Yellow","Blue"],
    inStock: true,
    category: "Dirt Bikes",
  },
  {
    id: "bike-6",
    name: "MINI NEOPLUS",
    price: "₹49,000",
    shortDescription: "Premium 50cc Mini Neoplus ATV with a 2-stroke petrol engine, automatic transmission, and all disc brakes.",
    fullDescription: "The 50cc Mini Neoplus ATV is designed for young riders who want a premium and stylish off-road vehicle. With its aggressive utility racks, self-start + pull start system, speed limiter, and remote shutoff kill switch, it offers safety, comfort, and thrilling performance.",
    images: [
      p("50cc-neo-plus-atv", 1),
      p("50cc-neo-plus-atv", 2),
      p("50cc-neo-plus-atv", 3),
      p("50cc-neo-plus-atv", 4),
      p("50cc-neo-plus-atv", 5),
      p("50cc-neo-plus-atv", 6),
      p("50cc-neo-plus-atv", 7),
      p("50cc-neo-plus-atv", 8),
      p("50cc-neo-plus-atv", 9),
      p("50cc-neo-plus-atv", 10),
    ],
    specifications: {
      "Engine Type": "50cc, 2-Stroke, Air-Cooled",
      "Transmission": "Automatic",
      "Starter System": "Self Start + Pull Start",
      "Braking System": "Front & Rear Disc Brakes",
      "Fuel Tank Capacity": "4 L",
      "Kerb Weight": "68 kg",
      "Max Load Capacity": "80 kg",
      "Ground Clearance": "150 mm",
      "Recommended Age": "8+ Years",
    },
    features: ["50cc Engine for Young Riders","Automatic Transmission","All Disc Brakes","Speed Limiter","Low Seat Height","Multiple Vibrant Colors","Electric Start","Remote Control Kill Switch"],
    colors: ["Orange","Black","Blue","Green","Red"],
    inStock: true,
    category: "ATV",
  },
  {
    id: "bike-19",
    name: "MINI NEO ATV",
    price: "₹45,000",
    shortDescription: "Vibrant 50cc Mini Neo ATV with a 2-stroke petrol engine, automatic transmission, and all disc brakes.",
    fullDescription: "The 50cc Mini Neo ATV is the perfect junior machine for young riders. Sporting a reliable 49cc 2-stroke single cylinder air-cooled engine and a fully automatic transmission, it is extremely easy and fun to handle. Front and rear disc brakes and spring absorbers ensure a secure and stable ride.",
    images: [
      p("50cc-mini-atv", 1),
      p("50cc-mini-atv", 2),
      p("50cc-mini-atv", 3),
      p("50cc-mini-atv", 4),
      p("50cc-mini-atv", 5),
      p("50cc-mini-atv", 6),
      p("50cc-mini-atv", 7),
    ],
    specifications: {
      "Engine Type": "49cc, Single Cylinder, 2-Stroke, Air-Cooled",
      "Transmission": "Automatic",
      "Starter System": "Self Start + Pull Start",
      "Braking System": "Front & Rear Disc Brakes",
      "Suspension": "Front & Rear Dual Spring Absorbers",
      "Tyres": "4.10-6 (Front) / 13x5.00-6 (Rear)",
      "Drive Train": "Chain Drive",
      "Fuel Capacity": "1 L",
      "Seat Height": "530 mm",
      "Max Speed": "45 km/h",
      "Max Load Capacity": "110 kg",
    },
    features: ["Junior Rider Dimensions","Easy Automatic Transmission","Electric Key Start & Pull Start","Front and Rear Cargo Racks","Dual Disc Brakes","Safety Lanyard Kill Switch"],
    colors: ["Orange","Black","Blue","Green","Red"],
    inStock: true,
    category: "ATV",
  },
  {
    id: "bike-8",
    name: "PIT BIKE",
    price: "₹85,000",
    shortDescription: "Powerful 125cc Four-Stroke Pit Bike with automatic transmission, self start, and all disc brakes.",
    fullDescription: "The 125cc Pit Bike offers a smaller frame profile with the raw, adrenaline-fueled power of a 4-stroke engine. Built with a reinforced steel frame, automatic transmission for ease of use, self-start convenience, and responsive hydraulic disc brakes to conquer trails with absolute confidence.",
    images: [
      p("125cc-pit-bike", 1),
      p("125cc-pit-bike", 2),
      p("125cc-pit-bike", 3),
      p("125cc-pit-bike", 4),
      p("125cc-pit-bike", 5),
      p("125cc-pit-bike", 6),
      p("125cc-pit-bike", 7),
    ],
    specifications: {
      "Engine Type": "125cc, Single Cylinder, 4-Stroke, Air-Cooled",
      "Transmission": "Automatic",
      "Starter System": "Self Start",
      "Braking System": "Front & Rear Disc Brakes",
      "Fuel Tank Capacity": "4.5 L",
      "Kerb Weight": "72 kg",
      "Max Load Capacity": "85 kg",
      "Ground Clearance": "260 mm",
    },
    features: ["125cc Four-Stroke Engine","Automatic Transmission","Electric Self Start","Hydraulic Wave Disc Brakes","Heavy-Duty Suspensions","High-Grip Off-Road Knobby Tyres"],
    colors: ["White","Black","Red","Blue","Yellow"],
    inStock: true,
    category: "Dirt Bikes",
  },
];

const heroImages = [
  "./public/products/50cc-mini-mouzer-atv-p1.png",
  "./public/products/50cc-dirt-bike-p1.png",
  "./public/products/125cc-pit-bike-p1.png"
];

const categories = [
  "All",
  "ATV",
  "Dirt Bikes"
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { bikesData, heroImages, categories };
}
